-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT (DISTINCT USER_ID) AS USERS
FROM ONLINE_SALE AS OS
JOIN (
    SELECT * 
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
    ) AS UI
USING (USER_ID)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER

# SELECT *
# FROM ONLINE_SALE