-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT ID, CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME IN ('Yogurt', 'Milk')
) AS SUB
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2
ORDER BY CART_ID;

# SELECT ID, CART_ID, NAME
# FROM CART_PRODUCTS
# WHERE NAME IN ('Yogurt', 'Milk');