-- 코드를 입력하세요
# SELECT * 
# FROM ( 
#    SELECT *, RANK() OVER (PARTITION BY M.CATEGORY ORDER BY M.TITLE DESC, M.ID DESC) AS RN  
#    FROM BOARD AS M 
# ) AS RANKING
# WHERE RANKING.RN <= 3

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT *, RANK() OVER (PARTITION BY RI.FOOD_TYPE ORDER BY RI.FAVORITES DESC) AS RRI
    FROM REST_INFO AS RI
) AS RANKING
WHERE RANKING.RRI <= 1
ORDER BY FOOD_TYPE DESC;