# 방법 (2) _ 추천
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS AS I
RIGHT JOIN ANIMAL_OUTS AS O
USING (ANIMAL_ID)
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;

# SELECT I.ANIMAL_ID, I.NAME
# FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
# ORDER BY TIMESTAMPDIFF(DAY, I.DATETIME, O.DATETIME) DESC
# LIMIT 2;