-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), 
MONTH(SALES_DATE), 
COUNT(DISTINCT(OS.USER_ID)) AS PUCHASED_USERS,
ROUND(
    (COUNT(DISTINCT(OS.USER_ID)))
    /
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021)
,1)
FROM ONLINE_SALE AS OS
JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS UI
ON OS.USER_ID = UI.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE);

# SELECT *
# FROM ONLINE_SALE
# WHERE YEAR(SALES_DATE) = 2022;

# SELECT *
# FROM USER_INFO;

# COUNT(
#     SELECT USER_ID
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021
# )

# SELECT *
# FROM ONLINE_SALE AS OS
# JOIN (
#     SELECT USER_ID, MONTH(JOINED) AS JM1
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021
# ) AS UI
# ON OS.USER_ID = UI.USER_ID
# JOIN (
#     SELECT MONTH(JOINED) AS JM2, COUNT (USER_ID) AS 
#     FROM USER_INFO
#     GROUP BY YEAR(JOINED), MONTH(JOINED)
# ) AS UI2
# ON UI.JM1 = UI2.JM2;

# SELECT COUNT(*)
# FROM ONLINE_SAL

# SELECT YEAR(JOINED), MONTH(JOINED), COUNT (USER_ID) AS 
# FROM USER_INFO
# GROUP BY YEAR(JOINED), MONTH(JOINED);

# SELECT   
#     YEAR(S.SALES_DATE)AS YEAR
#     ,MONTH(S.SALES_DATE)AS MONTH
#     ,(COUNT(DISTINCT(S.USER_ID))) AS PUCHASED_USERS
#     ,ROUND(
#         (
#             (COUNT(DISTINCT(S.USER_ID)))
#             /
#             (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021)
#         )
#         ,1)
#         AS PUCHASED_RATIO
# FROM ONLINE_SALE AS S
# LEFT JOIN USER_INFO AS U 
# ON S.USER_ID = U.USER_ID
# WHERE YEAR(U.JOINED) = 2021 
# GROUP BY YEAR,MONTH
# ORDER BY YEAR,MONTH
