-- 코드를 입력하세요
# SELECT *
# FROM FIRST_HALF;

# SELECT *
# FROM JULY;

SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS SUB
ON FH.FLAVOR = SUB.FLAVOR
ORDER BY (TOTAL_ORDER + TOTAL) DESC
LIMIT 3;