-- 코드를 입력하세요
# SELECT AI.NAME, AI.DATETIME
# FROM ANIMAL_INS AS AI
# LEFT JOIN ANIMAL_OUTS AS AO
# ON AI.ANIMAL_ID = AO.ANIMAL_ID
# WHERE AO.ANIMAL_ID IS NULL
# ORDER BY AI.DATETIME
# LIMIT 3;
# 방법 (2) : Join 과정에서 USING 사용
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AS AI
LEFT JOIN ANIMAL_OUTS AS AO
USING (ANIMAL_ID) # ANIMAL_ID 로 Join
WHERE AO.ANIMAL_ID IS NULL
ORDER BY AI.DATETIME
LIMIT 3;