# -- 코드를 입력하세요
SELECT FP.CATEGORY, MX AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MX
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS FS
ON FP.CATEGORY = FS.CATEGORY AND FP.PRICE = FS.MX
ORDER BY MAX_PRICE DESC;