-- 코드를 입력하세요

# SELECT ROUND(PRICE, -4) AS PRICE_GROUP
# FROM PRODUCT;

SELECT (
    CASE
    WHEN PRICE < 10000 THEN 0
    ELSE TRUNCATE(PRICE, -4)
    END
) AS PRICE_GROUP , COUNT(PRODUCT_ID)
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;

# SELECT * FROM PRODUCT;