# -- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, (SUM(SALES_AMOUNT) * P.PRICE) AS SALES
# FROM PRODUCT AS P
# LEFT JOIN OFFLINE_SALE AS O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# GROUP BY P.PRODUCT_ID
# ORDER BY SALES DESC, PRODUCT_CODE ASC;

SELECT T1.PRODUCT_CODE , (T2.COUNT * T1.PRICE) AS 'SALES'
FROM PRODUCT T1 
JOIN (
    SELECT SUM(SALES_AMOUNT) AS 'COUNT',OFFLINE_SALE_ID,PRODUCT_ID,SALES_AMOUNT,SALES_DATE 
    FROM OFFLINE_SALE 
    GROUP BY PRODUCT_ID
) T2 
ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC