# -- 코드를 입력하세요
# # SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.AMOUNT)
# # FROM FOOD_ORDER AS FO
# # JOIN FOOD_PRODUCT AS FP
# # ON FO.PRODUCT_ID = FP.PRODUCT_ID;

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.TOTAL) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
    FROM FOOD_ORDER
    WHERE MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID;

# SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
# FROM FOOD_ORDER
# WHERE MONTH(PRODUCE_DATE) = 5
# GROUP BY PRODUCT_ID