# -- 코드를 입력하세요
# # SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.AMOUNT)
# # FROM FOOD_ORDER AS FO
# # JOIN FOOD_PRODUCT AS FP
# # ON FO.PRODUCT_ID = FP.PRODUCT_ID;

SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * SUM(FO.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT *
    FROM FOOD_ORDER
    WHERE MONTH(PRODUCE_DATE) = 5
) AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID;