-- 코드를 입력하세요
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES AS P
LEFT JOIN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(ID) >1
) AS SP
ON P.HOST_ID = SP.HOST_ID
WHERE SP.HOST_ID IS NOT NULL
ORDER BY P.ID;
