-- 코드를 입력하세요
# SELECT P.ID, P.NAME, P.HOST_ID
# FROM PLACES AS P
# INNER JOIN (
#     SELECT HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(ID) >1
# ) AS SP
# ON P.HOST_ID = SP.HOST_ID
# ORDER BY P.ID;

SELECT *
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID 
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(ID) > 1
)
ORDER BY ID;