-- 코드를 입력하세요
# SELECT I.ANIMAL_ID, I.NAME
# FROM ANIMAL_INS AS I
# LEFT JOIN ANIMAL_OUTS AS O
# USING (ANIMAL_ID)
# WHERE O.ANIMAL_ID IS NOT NULL
# AND DATEDIFF(O.DATETIME, I.DATETIME) < 0
# ORDER BY I.DATETIME;

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
USING (ANIMAL_ID)
WHERE O.ANIMAL_ID IS NOT NULL
AND TIMEDIFF(O.DATETIME, I.DATETIME) < 0
ORDER BY I.DATETIME;